package at.tree.challenge.exception

class InternalErrorException : RuntimeException()
